config/routes.rb
Rails.application.routes.draw do
  root to: "controller#action"
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :price_per_night, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Links when logged in -->
      <%= link_to "Flats", flats_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Add a flat", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://avatars1.githubusercontent.com/u/42808135?v=4", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li></li>
          </ul>
        </div>
      </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="flex-container">
  <div class="row">
    <h1 class= "text-center">Find your flat</h1>
    <% @flats.each do |flat| %>
    <div class="card col-xs-6 col-md-4">
      <h3 class="card-title"><strong><%= flat.name %></strong></h3>
       <p class="card-text"><strong>Address: </strong><%= flat.address %></p>
       <p class="card-text"><strong>Description: </strong><%= flat.description %></p>
       <p class="card-text"><strong>Price per night: </strong><%= flat.price_per_night %></p>
       <p class="card-text"><strong>Number of guests: </strong><%= flat.number_of_guests %></p>
       <div class="flats-link">
       <%= link_to "Details", flat_path(flat), style: "font-size: 12px;" %>
       </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="formular">
  <h1 class="text-center">Add a new restaurant</h1>
  <%= simple_form_for [@flat] do |f| %>
    <div class="form-group">
    <%= f.input :name, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.input :address, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.input :price_per_night, class: "form-control" %>
    </div>
      <div class="form-group">
    <%= f.input :number_of_guests, class: "form-control" %>
    </div>
    <%= f.submit "add a review", class: "btn btn-primary " %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div>
  <h1><%= @flat.name %></h1>
  <p>Address: <%=  @flat.address %></p>
  <p>Price per night: <%=  @flat.price_per_night %></p>
  <p>Number of guests : <%=  @flat.number_of_guests %></p>
</div>

<div>
<i class="fas fa-undo"></i> <%= link_to "Back to list", flats_path %>
<br>
<br>
<i class="fas fa-edit"></i> <%= link_to "Edit", edit_flat_path(@flat) %>
</div>
<br>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

      <!-- Links when logged in -->
      <%= link_to "Flats", flats_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Add a flat", new_flat_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://avatars1.githubusercontent.com/u/42808135?v=4", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li></li>
          </ul>
        </div>
      </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= render "navbar" %>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>